// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnELeq1-eMVIK2y8vhZ0fBswxtoh7zigk',
    appId: '1:217335510648:web:be672e43cb962fea5adf8d',
    messagingSenderId: '217335510648',
    projectId: 'socialtanya-2d181',
    authDomain: 'socialtanya-2d181.firebaseapp.com',
    databaseURL: 'https://socialtanya-2d181.firebaseio.com',
    storageBucket: 'socialtanya-2d181.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEm7YaRM2dh5VEyxgv3jys0Cid-YkJY6Q',
    appId: '1:217335510648:android:04ea88d18ba6a91d',
    messagingSenderId: '217335510648',
    projectId: 'socialtanya-2d181',
    databaseURL: 'https://socialtanya-2d181.firebaseio.com',
    storageBucket: 'socialtanya-2d181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-uWuTGa3ZwgSw6rTAu66938u81eBiEo',
    appId: '1:217335510648:ios:04ea88d18ba6a91d',
    messagingSenderId: '217335510648',
    projectId: 'socialtanya-2d181',
    databaseURL: 'https://socialtanya-2d181.firebaseio.com',
    storageBucket: 'socialtanya-2d181.appspot.com',
    androidClientId:
        '217335510648-ddf60gbbbl01l2n87hkgi9q3ucqhm947.apps.googleusercontent.com',
    iosClientId:
        '217335510648-2nvh7jk26pc22uj9anqvr650sk65epbo.apps.googleusercontent.com',
    iosBundleId: 'com.ssa.socialtanya',
  );
}
